---
title: "Strings and Factors"
output: github_document
---

Viridis

```{r setup, echo = FALSE, message = FALSE}
library(tidyverse)


knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

Load the necessary libraries

```{r}
library(rvest) #facilitates web scraping
library(p8105.datasets)
```

## Let's do strings

```{r}
string_vec = c("my", "name", "is", "jeff")

str_detect(string_vec, "jeff") #looking for __ (case sensitive)

str_replace(string_vec, "jeff", "Jeff") #replaces strings that matches "jeff" to "Jeff"

str_replace(string_vec, "e", "E") #replaces strings that matches "e" to "E"
```

```{r}
string_vec = c(
  "i think we all rule for participating",
  "i think i have been caught",
  "i think this will be quite fun actually",
  "it will be fun, i think"
  )

str_detect(string_vec, "i think")
           
           
str_detect(string_vec, "^i think") #to find the str that STARTS with "i think"

str_detect(string_vec, "i think$") #to find the str that ENDS with "i think"
```

```{r}
string_vec = c(
  "Time for a Pumpkin Spice Latte!",
  "went to the #pumpkinpatch last weekend",
  "Pumpkin Pie is obviously the best pie",
  "SMASHING PUMPKINS -- LIVE IN CONCERT!!"
  )

str_detect(string_vec, "pumpkin")

str_detect(string_vec, "Pumpkin")

str_detect(string_vec, "PUMPKIN")

str_detect(string_vec,"[Pp]umpkin") #allow multiple options: either "P" or "p" and anything else after that to match "umpkin"
```


```{r}
string_vec = c(
  '7th inning stretch',
  '1st half soon to begin. Texas won the toss.',
  'she is 5 feet 4 inches tall',
  '3AM - cant sleep :('
  )

#pattern shows a number followed by two letters on three of them

str_detect(string_vec, "[0-9][a-zA-Z]") #give me any number between 0 and 9 and letter a to z and A to Z
```


More patterns to detect...

```{r}
string_vec = c(
  'Its 7:11 in the evening',
  'want to go to 7-11?',
  'my flight is AA711',
  'NetBios: scanning ip 203.167.114.66'
  )

#pattern: something that matches 7 something 11, can use "." because it will detect anything between 7 and 11

str_detect(string_vec, "7.11")
```

How things start to get real strange

```{r}
string_vec = c(
  'The CI is [2, 5]',
  ':-]',
  ':-[',
  'I found the answer on pages [6-7]'
  )

#say you're looking for special characters because by themselves there's a special meaning like "["?

str_detect(string_vec, "\\[") # "\" alone is a special character, so need "\\" before the special character you want to look for
```


## Factors ...

```{r}
sex_vec = factor(c("male", "male", "female", "female"))

#this automatically puts female first level alphabetically

as.numeric(sex_vec)
```

do some releveling...

```{r}
sex_vec = fct_relevel(sex_vec, "male") #can use relevel function to tell it which comes first

as.numeric(sex_vec)
```










```{r}
url = "http://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm"

drug_use_html = read_html(url)
```

```{r}
marj_use_df = 
  drug_use_html |> 
  html_table() |> 
  first() |> #takes first element out of the table or first table, can type in command line ?first to see if you can import an nth function to specify other elements
  slice(-1) #subtracts first row
```
